packages:
  - examples/*
  - vanity-h

catalog:
  '@types/node': ^26.6.3
  '@types/react': ^19.3.0
  preact: ^10.29.8
  react: ^19.3.0
  roxcss: ^0.0.3
  typescript: ^7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0-rc.1
  vite-plus: 1.0.0-rc.1
  vue: ^3.5.43

minimumReleaseAgeExclude:
  - '@types/node@26.6.3'
  - roxcss@0.0.3
overrides:
  vite: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
